name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Grant execute permissions to Gradle
        run: chmod +x gradlew

      - name: Validate Gradle Wrapper
        run: ./gradlew --version

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: viber-telegram-forwarder-debug
          path: app/build/outputs/apk/debug/app-debug.apk
          retention-days: 5

      - name: Build Release APK
        run: ./gradlew assembleRelease --stacktrace
        continue-on-error: true

      - name: Upload Release APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: viber-telegram-forwarder-release
          path: app/build/outputs/apk/release/app-release.apk
          retention-days: 5
